from bwt_optimised_sp import *

def testSpBWTOptimised():
    assert spCalculateBurrowsWheelerTransform('GATGAN$') == 'NGGT$AA'

    assert spCalculateBurrowsWheelerTransform('TTTGGANNGATCAAAC$') == 'CCAAGGATGNTNAATT$'

    assert spCalculateBurrowsWheelerTransform('TAAGAGAATTCAAAATAAAATGGTGGACTGGATTCAATCAAGAATTTGGAGATCAAACTAATGTGATCAG$') == 'GCTCAAACTACATGGAGCGAAGAGAGAAAGATTTTTAAAAAGAGATGTTTTTGA$CTAATAGGTCAAAATA'

    assert spCalculateBurrowsWheelerTransform('CTCTTAGTTCTCCTACTATTCCCACTCACTCTAAAATAACCATTGTACTCAAAGTCTTTGTAGAAGTGGA$') == 'AGTCATAGAATTCCTAATATCTCTCCATTTCAAATA$TTGATTTAAACACGGTCCCTCCTCGGTTCAGATC'

testSpBWTOptimised()
